services:
  api:
    build: backend
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - REDIS_URL=redis://redis:6379/0

      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      redis:
        condition: service_healthy
      dynamodb:
        condition: service_started
      init:
        condition: service_completed_successfully

  # frontend:
  #   build: 
  #     context: frontend
  #   depends_on:
  #     api:
  #       condition: service_started

  dynamodb:
    image: amazon/dynamodb-local
    container_name: db
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./volumes/dynamodb:/home/dynamodblocal/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  init:
    build: backend
    container_name: init
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - dynamodb
    volumes:
      - ./infra/:/app/infra/:ro
    command: python infra/local/init_db.py --table-file infra/config/tables.json
