name: discord-clone
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - packaging=25.0=py312hca03da5_1
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h2bfc596_1
  - readline=8.3=h0b18652_0
  - setuptools=80.10.1=py312hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - boto3==1.42.36
      - botocore==1.42.36
      - click==8.3.1
      - fastapi==0.128.0
      - h11==0.16.0
      - idna==3.11
      - jmespath==1.1.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - s3transfer==0.16.0
      - six==1.17.0
      - starlette==0.50.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uvicorn==0.40.0
prefix: /opt/homebrew/anaconda3/envs/discord-clone
