services:
  api:
    deploy:
      replicas: 4

  lb:
    image: nginx:alpine
    container_name: lb
    ports:
      - "80:80"
      - "8000:80"
      - "3000:80"
    volumes:
      - ./infra/local/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - frontend
      - api

  frontend:
    build:
      args:
        - NODE_ENV=development
        - NEXT_PUBLIC_API_ENDPOINT=http://localhost:80
        - INTERNAL_API_ENDPOINT=http://lb:80
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_ENDPOINT=http://localhost:80
      - INTERNAL_API_ENDPOINT=http://lb:80
    deploy:
      replicas: 4